# Generated by Django 3.1.12 on 2021-09-19 03:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('record_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.record')),
                ('revenue_type', models.CharField(choices=[('reimb', 'Reimbursement'), ('rent', 'Rent')], default='rent', max_length=50)),
            ],
            bases=('transactions.record',),
        ),
        migrations.AlterField(
            model_name='record',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 18, 22, 28, 24, 226327)),
        ),
    ]
