# Generated by Django 3.1.12 on 2022-01-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raw_invoice',
            name='need_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='raw_invoice',
            name='note',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
