# Generated by Django 3.1.12 on 2022-01-04 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20220103_2203'),
        ('transactions', '0002_auto_20220102_1347'),
    ]

    operations = [
    ]
