# Generated by Django 3.1.12 on 2021-09-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20210918_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date_uploaded',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
