# Generated by Django 3.1.12 on 2021-07-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='stmt_type',
            field=models.CharField(default='na', max_length=10),
            preserve_default=False,
        ),
    ]
