# Generated by Django 3.1.12 on 2021-07-28 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_stmt_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='stmt_account_last4',
            new_name='account_number',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='stmt_type',
            new_name='statement_type',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='stmt_amount',
            new_name='transaction_amount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='stmt_date',
            new_name='transaction_date',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='stmt_description',
            new_name='transaction_description',
        ),
    ]
