# Generated by Django 3.1.12 on 2021-09-19 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20210918_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='market_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='transactions.rental_unit'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='match_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
