# Generated by Django 3.1.12 on 2021-07-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20210728_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='statement_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_description',
            field=models.TextField(max_length=500),
        ),
    ]
