# Generated by Django 3.1.12 on 2021-08-03 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20210729_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='invoice_image',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_verified',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
