# Generated by Django 3.1.12 on 2022-01-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20220106_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raw_invoice',
            name='note',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
    ]
