# Generated by Django 3.1.12 on 2021-08-03 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20210802_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_type',
            new_name='accounting_classification',
        ),
    ]
