# Generated by Django 3.1.12 on 2022-01-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20220107_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_ignored',
            field=models.BooleanField(default=False),
        ),
    ]
