# Generated by Django 3.1.12 on 2021-08-05 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20210802_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='invoice_image',
            new_name='document_image',
        ),
    ]
