# Generated by Django 3.1.12 on 2022-02-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_transaction_is_ignored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(blank=True, choices=[('misc', 'Misc'), ('advertising', 'Advertising'), ('management_fee', 'Management Fee'), ('trash', 'Trash'), ('water', 'Water'), ('power', 'Power'), ('insurance', 'Insurance'), ('repair_maintenance', 'Repair and Maintenance'), ('roof', 'Roof'), ('landscaping', 'Landscaping'), ('commission', 'Commission'), ('taxes_and_fess', 'Taxes & Fees'), ('payroll', 'Payroll')], max_length=50, null=True),
        ),
    ]
