# Generated by Django 3.1.12 on 2022-02-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_auto_20220222_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='raw_invoice',
            name='tax_year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
