# Generated by Django 3.1.12 on 2021-08-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_auto_20210813_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_unit',
            name='suite',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
