# Generated by Django 3.1.12 on 2022-03-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_auto_20220303_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_unit',
            name='suite',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
