# Generated by Django 3.1.12 on 2021-08-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_auto_20210814_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='invoice_image',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
