# Generated by Django 3.1.12 on 2021-08-30 05:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0012_expense_invoice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 30, 0, 41, 48, 789171)),
        ),
        migrations.AlterField(
            model_name='expense',
            name='note',
            field=models.TextField(max_length=500),
        ),
    ]
