# Generated by Django 3.1.12 on 2021-08-31 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_auto_20210830_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 30, 20, 55, 18, 390125)),
        ),
    ]
