# Generated by Django 3.1.12 on 2022-03-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_auto_20220312_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='is_verified',
        ),
    ]
