# Generated by Django 3.1.12 on 2022-03-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_remove_statement_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raw_invoice',
            name='upload_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
