# Generated by Django 3.1.12 on 2021-09-01 00:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_auto_20210830_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='transactions.rental_unit'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 31, 19, 48, 8, 143354)),
        ),
    ]
