# Generated by Django 3.1.12 on 2022-04-03 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_auto_20220330_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='raw_invoice',
            name='file_hash',
            field=models.TextField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
