# Generated by Django 3.1.12 on 2021-09-04 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_auto_20210831_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 4, 4, 4, 1, 53188)),
        ),
    ]
