# Generated by Django 3.1.12 on 2022-05-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_auto_20220403_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raw_invoice',
            name='invoice_image',
            field=models.TextField(max_length=500),
        ),
    ]
