# Generated by Django 3.1.12 on 2021-09-09 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_auto_20210907_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='match_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 8, 22, 31, 22, 356371)),
        ),
    ]
