# Generated by Django 3.1.12 on 2022-05-11 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_auto_20220511_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raw_invoice',
            old_name='invoice_image',
            new_name='invoice_link',
        ),
    ]
