# Generated by Django 3.1.12 on 2022-05-12 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0020_auto_20220511_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raw_invoice',
            old_name='invoice_link',
            new_name='invoice_image',
        ),
    ]
