# Generated by Django 4.0.4 on 2022-06-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_auto_20220512_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='full_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
