# Generated by Django 4.0.4 on 2022-09-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0023_rename_market_price_property_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='market_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
