# Generated by Django 4.1.4 on 2023-06-28 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0029_rename_is_available_rental_unit_is_current_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='address',
            field=models.ForeignKey(limit_choices_to={'is_current': True}, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='transactions.rental_unit'),
        ),
    ]
