# Generated by Django 5.0 on 2024-01-11 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0030_alter_record_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='document_hash',
            field=models.TextField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='transactions.rental_unit'),
        ),
    ]
