# Generated by Django 5.0 on 2024-01-12 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0031_record_document_hash_alter_record_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='document_hash',
        ),
    ]
