# Generated by Django 5.0 on 2024-01-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0032_remove_record_document_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='document_hash',
            field=models.TextField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
